Ringbuffer and Exponential retry made user-configurable
zeebe-io/zeeqs pull request #59
Opened 2020-09-09 17:09 UTC by strawhat5

- Ringbuffer name can be given in application.yaml
- Hazelcast exponential retry props can also be configured
- Hazelcast config naming aligned with [zeebe-simple-monitor](https://github.com/zeebe-io/zeebe-simple-monitor#configuration)
- Fixed GraphiQL url in README

2020-09-09 17:10 UTC, strawhat5 commented
Hey @saig0 I have made some changes to Hazelcast connection configs, to allow more user-configurability. Could you please take a look at this PR?

2020-09-10 03:54 UTC, saig0 commented
@strawhat5 thank you for your contribution :+1: 
I'll look at it soon :rocket:

2020-09-11 05:25 UTC, saig0 requested changes
Looks good :tada: Thanks :cookie: 

Just some small things.

BTW: why do you need the additional retry configuration options?

2020-09-11 05:25 UTC, saig0 commented on README.md
> +  http://localhost:9000/graphiql
This is the query HTTP request for the GraphQL endpoint :grin: 

It is not the link to GraphiQL. In GraphiQL, the queries are build and executed in the UI. Here, I want to give a simple example for querying the (real) GraphQL endpoint using `curl`.

2020-09-11 05:25 UTC, saig0 commented on hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastProperties.kt
> +        val connectionMaxBackoff: Int = 60 * 1000
I would prefer to configure the `connectionInitialBackoff` and `connectionMaxBackoff` as a duration string instead of a number. So, it is similar to `connectionTimeout`. And it clarifies the unit of the number/value.

2020-09-11 05:25 UTC, saig0 commented on app/src/main/resources/application.yml
> +        connectionMaxBackoff: 60000
We should update the documentation and list the new configuration options.

2020-09-11 12:10 UTC, strawhat5 commented on README.md
> +  http://localhost:9000/graphiql
Ah my bad for not reading the doc properly. 😅 I have fixed this.

2020-09-11 12:11 UTC, strawhat5 commented on hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastProperties.kt
> +        val connectionMaxBackoff: Int = 60 * 1000
Makes sense, I have updated it.

2020-09-11 12:11 UTC, strawhat5 commented on app/src/main/resources/application.yml
> +        connectionMaxBackoff: 60000
Yep, done!

2020-09-11 12:17 UTC, strawhat5 commented
@saig0 I have made the changes as per your suggestions. Please review it and let me know your inputs.

>BTW: why do you need the additional retry configuration options?

In cases where hazelcast (remote) cluster goes down and we experience an elongated downtime, and it would help to retry with exponential backoff option (rather than a fixed continuous retry every 15 seconds).

2020-09-14 04:18 UTC, saig0 approved these changes
Thanks :cake:

2020-09-14 04:18 UTC, merged

2020-09-14 04:40 UTC, strawhat5 commented
Thanks @saig0 ! Can you please create a release for this? I would like to start using the docker image right away. 🙂

2020-09-14 04:42 UTC, saig0 commented
Okay. I'm building a new release :+1:

2020-09-14 05:16 UTC, saig0 commented
Done: https://github.com/zeebe-io/zeeqs/releases/tag/1.0.0-alpha4 :balloon:

2020-09-14 05:17 UTC, strawhat5 commented
Great, thanks! 🙏